### ISSUE TITLE
When training SensatUrban, MIou is low. 

### ISSUE THREAD

**Issue by YangJieDing** [QingyongHu/SQN#21]
labeled point = 0.1%,the configuration uses https://github.com/QingyongHu/SensatUrban/blob/master/tool.py.
When I trained, the MIou value remained around 4.4, even though I trained more than 80 epochs.
![image](https://github.com/QingyongHu/SQN/assets/54899891/bec649e3-4e8e-4928-940c-ee4924c9cc68)
What is the reason for this?

**Comment by YangJieDing** [comment]
The issue has been resolved

**Comment by jianGao555** [comment]
> The issue has been resolved

Hi, did you implement the running code on the SensatUrban dataset yourself?
