### ISSUE TITLE
How to product the video/gif illustrating the performance?

### ISSUE THREAD

**Issue by UncleSan** [QingyongHu/SQN#6]
Hi! @QingyongHu , thank you for sharing your awsome works.
I would like to know how you product the videos/gifs (like [this](https://github.com/QingyongHu/SQN/blob/main/imgs/SensatUrban.gif)) illustrating the semantic segmentation  results?
Would you like to share the code or the software?
Thanks again.

**Comment by QingyongHu** [comment]
Hi @UncleSan ,

Thanks for your interest in our work!

We actually made the video using Blender, please refer to this [video ](https://www.youtube.com/watch?v=eXct_7k779Q&t=9s)to have an idea of how to create animation.

I hope this could be helpful.

**Comment by UncleSan** [comment]
@QingyongHu  Thank you! It is really helpful.
